export const APP_TITLE = 'Relentless';
export const ACCESS_TOKEN_COOKIE_NAME = 'ACCESS_TOKEN';
export const ACCESS_TOKEN_EXPIRATION_SECONDS = 60 * 15; // 15 minutes
export const REFRESH_TOKEN_COOKIE_NAME = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_EXPIRATION_SECONDS = 60 * 60 * 24 * 7; // 7 days
export const VERIFICATION_PIN_EXPIRATION_SECONDS = 15 * 60; // 15 minutes
export const TOAST_COOKIE_NAME = 'TOAST';
export const TOAST_COOKIE_EXPIRATION_SECONDS = 60;
export const SERVICE_EMAIL = 'no-reply@mail.by-ironex.com';
export const SECURITY_EMAIL = 'security@mail.by-ironex.com';
